title: One Grizzled Developer
author: P. Komkai
email: alyerin@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Can't really think of much of a description for this blog, since it hasn't really taken off yet.
  Maybe someday I'll come back and change this to something more meaningful.

# social links
twitter_username: alyerin # DO NOT include the @ character, or else the build will fail!
github_username:  alyerin # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
